queue_rules:
  - name: high-priority
    queue_conditions:
      - label = reviewed
      - label = high priority
      - check-success = Ruby
    queue_branch_prefix: merge_queue_high_
    allow_checks_interruption: true

  - name: default
    queue_conditions:
      - label = reviewed
      - -label = high priority
      - check-success = Ruby
    queue_branch_prefix: merge_queue_
    allow_checks_interruption: true

    priority_rules:
      - name: cve
        conditions:
          - label = cve

merge_queue:
  max_parallel_checks: 4

pull_request_rules:
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: Label first PR of Mergify Stacks PRs
    description: The first PR of a Mergify stack should be labeled as such
    conditions:
      - "body ~= ^Change-Id:"
      - -base ~= ^mergify_cli/
    actions:
      label:
        toggle:
          - top of the stack

  - name: Automatic add the queue when reviewed
    conditions:
      - label = reviewed
    actions:
      queue:
        merge_method: merge
