queue_rules:
  - name: default
    queue_conditions:
      - label = reviewed
    queue_branch_prefix: merge
merge_queue:
  max_parallel_checks: 4
pull_request_rules:
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: Label first PR of Mergify Stacks PRs
    description: The first PR of a Mergify stack should be labeled as such
    conditions:
      - "body ~= ^Change-Id:"
      - -base ~= ^mergify_cli/
    actions:
      label:
        toggle:
          - top of the stack
