name: Notify Deployment
# This workflow is triggered when a deployment PR is closed

on:
  pull_request:
    types: [closed]
    branches: [master] # [production] in the real repo

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Echo the PR details
      run: |
        echo "PR number is ${{ github.event.pull_request.number }}"
        echo "PR title is ${{ github.event.pull_request.title }}"
        echo "PR has been merged ${{ github.event.pull_request.merged }}"
        echo "PR body is ${{ github.event.pull_request.body }}"

    - name: Send GitHub Action data to a Slack workflow
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.BANCOBOT_GITHUB_API_TOKEN }}
        webhook-type: incoming-webhook
        payload: |
          text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
