name: Notification

on:
  pull_request:
    types: [closed]
    branches: [master]

env:
  channel: "C07B364NPHB" # #builds-test

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Echo the PR details
      run: |
        echo "PR number is ${{ github.event.pull_request.number }}"
        echo "PR title is ${{ github.event.pull_request.title }}"
        echo "PR has been merged ${{ github.event.pull_request.merged }}"
        echo "PR body is ${{ github.event.pull_request.body }}"

    - name: Notify in Slack
      id: slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ secrets.BANCOBOT_GITHUB_API_TOKEN }}
        payload: |
          channel: ${{ env.channel }}
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: ${{ toJSON(github.event.pull_request.body) }}
