name: Notification

on:
  pull_request:
    types: [closed]
    branches: [master]

env:
  channel: "#builds-test"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Echo the PR details
      run: |
        echo "PR number is ${{ github.event.pull_request.number }}"
        echo "PR title is ${{ github.event.pull_request.title }}"
        echo "PR has been merged ${{ github.event.pull_request.merged }}"
        echo "PR body is ${{ github.event.pull_request.body }}"

    - name: Notify in Slack
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.event.pull_request.body }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.BANCOBOT_GITHUB_API_TOKEN }}
        SLACK_WEBHOOK_TYPE: ${{ env.channel }}
